import Head from 'next/head';
import Image from 'next/image';
import { Button } from '../components/Button/Button';
import { Navbar } from '../components/header/navbar';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				{/* pr afficher ma barre de navigation sur le navigateur internet */}
			</Head>

			<Navbar />

			<main className={styles.main}></main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
