import Head from 'next/head';
import Image from 'next/image';
import { Button } from '../components/Button/Button';
import { Navbar } from '../components/header/navbar';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				{/* font awesome */} 
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
			</Head> 

			{/* pr afficher ma barre de navigation sur le navigateur internet */} 
			<Navbar />

			<main className={styles.main}></main> 

			<footer className={styles.footer}></footer>
		</div>
	);
}
